{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "name": "Allen.ipynb",
      "provenance": [],
      "collapsed_sections": [],
      "authorship_tag": "ABX9TyMmj7l2zmCY5VuT2HU+QRac"
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    }
  },
  "cells": [
    {
      "cell_type": "code",
      "metadata": {
        "id": "z_agL6MzcQoq",
        "colab_type": "code",
        "colab": {}
      },
      "source": [
        "'''\n",
        "Name: header / <h2 class: \"node-title\">.text \n",
        "Acronym \n",
        "Co-located <div class : \"field-item even\"> \n",
        "Submission Date: <span class : date-display-single>\n",
        "Notification Date \n",
        "Conference Date\n",
        "Location <div class : \"field-item even\"> \n",
        "'''\n",
        "\n",
        "import requests\n",
        "import time\n",
        "from bs4 import BeautifulSoup\n"
      ],
      "execution_count": 0,
      "outputs": []
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "LOKtKtq9cUkX",
        "colab_type": "code",
        "outputId": "3244daf2-7a7a-4d75-c126-d2452497c938",
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 70
        }
      },
      "source": [
        "def eventExtractor(html_string):\n",
        "    response = requests.get(html_string)\n",
        "    soup = BeautifulSoup(response.content, \"html.parser\")\n",
        "\n",
        "    contentBlock = soup.find_all(\"article\")\n",
        "\n",
        "    #missing bolded \"updated\" and \"deadline for submission\" text \n",
        "\n",
        "    event = [] \n",
        "    for article in contentBlock:\n",
        "        rawText = '' \n",
        "        \n",
        "        for title in (article.find_all(\"h2\", {\"class\" : \"node-title\"})):\n",
        "            if(title.text.strip() == \"\"):\n",
        "                continue\n",
        "            rawText += title.text.strip()+'\\n'\n",
        "\n",
        "        for loc in (article.find_all(\"div\", {\"class\" : \"field-items\"})): \n",
        "            if(loc.text.strip() == \"\"):\n",
        "                continue\n",
        "            rawText += loc.text.strip()+'\\n'\n",
        "        \n",
        "        event.append(rawText)\n",
        "\n",
        "    return event \n",
        "\n",
        "\n",
        "data = [] \n",
        "\n",
        "for x in range(3):\n",
        "    url = \"https://call-for-papers.sas.upenn.edu/category/all/backtrack?page={}\".format(x)\n",
        "    print(url)\n",
        "    pageEvent = eventExtractor(url)\n",
        "    data += (pageEvent)\n",
        "\n",
        "\n",
        "\n"
      ],
      "execution_count": 26,
      "outputs": [
        {
          "output_type": "stream",
          "text": [
            "https://call-for-papers.sas.upenn.edu/category/all/backtrack?page=0\n",
            "https://call-for-papers.sas.upenn.edu/category/all/backtrack?page=1\n",
            "https://call-for-papers.sas.upenn.edu/category/all/backtrack?page=2\n"
          ],
          "name": "stdout"
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "jHTfKhBGuRmc",
        "colab_type": "code",
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 1000
        },
        "outputId": "ab69b193-9eac-4c1e-8fec-8dc384f30e3b"
      },
      "source": [
        "data"
      ],
      "execution_count": 27,
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "['International Journal of Information Technology (IJIT)\\nFriday, February 28, 2020 - 2:16am\\nbook publisher\\nSunday, March 1, 2020\\nInternational Journal of Information Technology (IJIT)\\nISSN : 1834-624N 2974-5962 (Print)\\n***February Issue ***http://flyccs.com/jounals/IJIT/Home.html\\n\\xa0\\nScope\\n',\n",
              " 'International Journal of Education\\nThursday, February 27, 2020 - 9:09pm\\nbook publisher\\nSaturday, February 29, 2020\\nInternational Journal of Education (IJE) \\nISSN : 1839-519N 2974-5962 (Print)***February Issue ***\\nhttp://flyccs.com/jounals/IJEMS/Home.html\\xa0 \\n\\xa0\\n\\xa0\\nScope\\n',\n",
              " 'Call for chapters: Call Me by Your Name edited collection\\nThursday, February 27, 2020 - 6:47pm\\nDr. Edward Lamberti and Professor Michael Williams\\nMonday, April 6, 2020\\nCall for chapters: Call Me by Your Name edited collection\\n\\xa0\\nEditors: Edward Lamberti and Michael Williams\\n',\n",
              " 'Human Cognition in Andreï Makine’s Oeuvre\\nThursday, February 27, 2020 - 12:51pm\\nLuxembourg School of Religion & Society\\nFriday, May 15, 2020\\nHuman Cognition in Andreï Makine’s Oeuvre\\nLa cognition humaine chez Andreï Makine\\n\\xa0\\n\\xa0\\nJournées d’études organisées par Luxembourg School of Religion & Society\\nStudy days organized by Luxembourg School of Religion & Society\\n\\xa0 \\xa0 \\xa0 \\xa0 \\xa0 \\xa0 \\xa0 \\xa0 \\xa0 \\xa0 \\xa0 \\xa0 \\xa0 \\xa0 \\xa0 \\xa0 \\xa0 \\xa0 \\xa0 \\xa0 \\xa03 et 4 décembre 2020 – December 3-4, 2020\\nOrateur invite – keynote speaker:\\n',\n",
              " 'Digital Methodology in the Linguistic Study of Literature: Theory\\nThursday, February 27, 2020 - 12:46pm\\nMLA 2021 Annual Conv Linguistics and Literature Forum Exec Comm\\nMonday, March 23, 2020\\nDigital Methodology in the Linguistic Study of Literature: Theory\\nLinguistics and Literature Forum Session 1\\nMLA 2021 Annual Convention, Toronto, Jan 7-10\\nDigital tools have indisputably made many tasks in the linguistic study of literature much easier and faster than used to be. But the turn to digital methods has brought more than ease and efficiency; it has forever changed the field. What are the ways in which digital tools have shaped the linguistic study of literature? And what are the ways literary studies has itself inspired innovation, methods, and the development of new digital tools?\\n',\n",
              " 'Digital Methodology in the Linguistic Study of Literature: Practice\\nThursday, February 27, 2020 - 12:46pm\\nMLA Annual Conv 2021 Linguistics and Literature Forum Session\\nMonday, March 23, 2020\\nDigital Methodology in the Linguistic Study of Literature: Practice\\nLinguistics and Literature Forum Session 2\\nMLA 2021 Annual Convention, Toronto, Jan 7-10\\nDigital tools have become increasingly more important in the linguistic study of literature; for instance, they allow us to streamline much of our work. In what ways have digital methods made your work easier or more efficient? Do some tools lend themselves better to particular problems? What best practices have scholars found as they manage programs and data?\\n',\n",
              " 'MLA 2021 “#OwnVoices in Children’s and Adolescent Literature”\\nThursday, February 27, 2020 - 12:46pm\\nMLA GS Children’s and Young Adult Literature Forum\\nTuesday, March 10, 2020\\nMLA 2021 “#OwnVoices in Children’s and Adolescent Literature”\\nGuaranteed Session Sponsored by the MLA GS Children’s and Young Adult Literature Forum\\nToronto, Ontario\\nJanuary 7-10, 2021\\nPanel Chair:\\xa0 Brigitte Fielder\\n\\xa0\\nDeadline for submissions: 10 March 2020\\n',\n",
              " 'Old and new African Diaspora Networks: Intersections, Distinctions and Strategies\\nThursday, February 27, 2020 - 12:45pm\\nAfrican Centre for the Study of the United States, Wits\\nWednesday, April 1, 2020\\nThe conference will bring together scholars and intellectuals from the African diaspora, and/or those engaged in African diaspora research and engagement. It will offer perspectives on old and new diaspora from various theoretical, conceptual and disciplinary perspectives. The aim is to generate new knowledge that can inform not only scholarship but also work in the policy/government, civil society and business spheres.\\nThe conference is calibrated as an interdisciplinary, transdisciplinary and multidisciplinary congregation. Multiple viewpoints from which old and new diaspora can be explained and comprehended will be presented.\\n',\n",
              " 'First Generation PhDs in the Academy\\nThursday, February 27, 2020 - 12:45pm\\nMLA 2021 Special Session\\nMonday, March 16, 2020\\n\"While there is a growing and prominent literature on the experiences of first-generation undergraduate students, there is a lack of research on the experiences of first-generation\\xa0graduate\\xa0students. People tend to assume that if someone makes it through the bachelor’s degree, they enter graduate school on a level playing field.\" - Bailey Smolarek, Inside Higher Ed\\nThis proposed roundtable session for MLA 2021 seeks to explore the challenges and experiences faced by\\xa0first-generation PhDs, both as graduate students and in their post-graduate careers. Some possible topics for exploration include:\\n',\n",
              " 'Short Fiction Criticism, SCMLA 2020\\nThursday, February 27, 2020 - 12:44pm\\nSouth Central Modern Language Association\\nMonday, March 23, 2020\\nNow accepting proposals for the Short Fiction Criticism panel at the South Central Modern Language Association conference in Houston, Texas, October 8-10, 2020.\\nPapers critically engaging short fiction in any language or time period will be considered. Approaches that engage the conference theme “Politics of Protest” are encouraged, as are papers that expand the definition of short fiction as a genre (to include, for example, graphic literature or digital media narratives).\\nPlease submit abstracts to Sarah Peters at speters@ecok.edu by March 23, 2020.\\n',\n",
              " 'In the Wake of Red Power Movements. New Perspectives on Indigenous Intellectual and Narrative Traditions\\nThursday, February 27, 2020 - 12:44pm\\nInstitute of Advanced Study, University of Warwick\\nSunday, March 15, 2020\\nThis symposium explores North American Indigenous intellectual and narrative traditions that were recovered, reclaimed, or (re-)invented in the wake of Red Power movements that emerged in the 1960s in the settler colonial societies of Canada and the USA. It asks: which new perspectives and visions have been developed over the last 50 years within Indigenous studies and related fields when looking at Indigenous land and land rights, Indigenous political and social sovereignty, extractivism and environmental destruction, oppressive sex/gender systems, and for describing the repercussions of settler colonialism in North America, especially in narrative representations?\\n',\n",
              " 'Writing the Heavens. Celestial Observation in Literature, 800--1800 (May 20-22, 2021, Bamberg, Germany)\\nThursday, February 27, 2020 - 12:44pm\\nAura Heydenreich, Florian Klaeger, Klaus Mecke, Dirk Vanderbeke, Jörn Wilms - ELINAS (Center for Literature and Natural Science)\\nSunday, May 31, 2020\\nIn the Middle Ages and early modernity, celestial observation was frequently a subject for verbal rather than numerical and geometrical recording. Astronomical genres, in the hands of natural philosophers, poets, chroniclers, travellers, geographers, educators and others mediated knowledge of the heavens in textual form. Before the modern academic institutionalization of astronomy, such celestial knowledge extended from the cosmological to the meteorological, with applications and implications that touched upon a wide range of discourses, be they theological, legal, political, medical or agricultural.\\n',\n",
              " 'Sidney and the Sidney Circle at SCSC 2020 (3 panels)\\nThursday, February 27, 2020 - 12:44pm\\nInternational Sidney Society\\nTuesday, March 31, 2020\\nSIDNEY AND THE SIDNEY CIRCLE AT THE SIXTEENTH-CENTURY SOCIETY CONFERENCE\\nOctober 29-November 1, 2020, Baltimore, MD\\nThe International Sidney Society will sponsor three panels at the 2020 Sixteenth-Century Society Conference and invites paper proposals related to Philip Sidney, Mary Sidney Herbert, Lady Mary Wroth, the Sidney Family or the Sidney Circle generally.\\nI.\\xa0 Post-critical Reading and the Sidney Circle\\n',\n",
              " 'MLA 2021 | Breaking Textual Boundaries: Collaborative Writing and Multiple Authorship\\nThursday, February 27, 2020 - 12:44pm\\nViviana Pezzullo\\nTuesday, March 10, 2020\\nMLA 2021\\nToronto (Canada) \\n7-10 January, 2021\\nBreaking Textual Boundaries: Collaborative Writing and Multiple Authorship\\n',\n",
              " 'The 2021 MLA Call for Papers\\nThursday, February 27, 2020 - 12:44pm\\nLLC Pre-14th-Century Chinese Forum\\nSunday, March 15, 2020\\nThe 2021 General Call for Papers\\n\\xa0(LLC Pre-14th-Century Chinese Forum)\\n(MLA Annual Convention Jan 7-10, 2021, Toronto)\\xa0The following is a summary of call for papers from three panel sessions. The deadline of abstract submission is March 15, 2020.\\xa0Abstract submission details are at the end of each panel description.\\n\\xa0\\n1.\\xa0\\xa0\\xa0\\xa0\\xa0 Panel Title: Animal Perversions\\n\\xa0\\nShort description:\\nThis session will examine the eroticization (or non-eroticization) of particular animals within the pre-14th century Chinese cultural sphere, with specific attention to questions of sexuality, fetish, ethics, and species identity.\\n\\xa0\\nDetails:\\n',\n",
              " '\"Where are the Wonder Girls? Heroines and Persistence in Campus Novels\"\\nThursday, February 27, 2020 - 12:44pm\\nModern Language Association\\nSunday, March 15, 2020\\n\"Where are the Wonder Girls?\\xa0Heroines\\xa0and\\xa0Persistence\\xa0in\\xa0Campus Novels\"\\xa0\\n\\xa0\\nCall for Papers\\nModern Language Association Convention\\nToronto, Ontario\\nJanuary 7-10, 2021\\n',\n",
              " 'International Journal of Humanities, Art and Social Studies (IJHAS)\\nThursday, February 27, 2020 - 2:48am\\npublisher\\nSaturday, February 29, 2020\\n***February Issue ***\\nhttp://flyccs.com/jounals/IJHASS/Home.html\\n\\xa0 \\xa0 \\xa0 \\xa0 \\xa0 \\xa0 \\xa0 \\xa0 \\xa0 \\xa0 \\xa0 \\xa0 \\xa0 \\xa0 \\xa0 \\xa0 \\xa0 \\xa0 \\xa0 \\xa0 \\xa0 \\xa0 \\xa0 \\xa0 \\xa0 \\xa0 \\xa0 \\xa0 \\xa0 \\xa0 \\xa0 \\xa0 \\xa0 \\xa0 \\xa0 \\xa0 \\xa0 \\xa0 \\xa0 \\xa0 \\xa0 \\xa0 \\xa0 \\xa0 \\xa0 \\xa0 \\xa0 \\xa0 \\xa0 \\xa0 \\xa0 \\xa0 \\xa0 \\xa0 \\xa0 \\xa0 \\xa0 \\xa0 \\xa0 \\xa0 \\xa0 Paper Submission :\\xa0Submission System.\\n\\xa0\\nScope\\n',\n",
              " 'PORTALS: A Journal of Comparative Literature, Spring 2020 edition\\nThursday, February 27, 2020 - 2:38am\\nComparative Literature Student Association, San Francisco State University\\nFriday, March 13, 2020\\nThe Comparative Literature Student Association (CLSA) at San Francisco State University is accepting submissions for the\\xa0\\nSpring 2020 edition of the literary journal Portals.\\xa0\\nPortals is San Francisco State University’s global journal for scholarship in comparative and world literature. We publish student research, both from San Francisco State University and from universities around the world. Past volumes may be accessed at http://portalsjournal.com/. We will publish our more recent publications, including this year’s submissions, on this website.\\n',\n",
              " 'International Journal of Education(IJE)\\nWednesday, February 26, 2020 - 9:02pm\\nbook publisher\\nSaturday, February 29, 2020\\nInternational Journal of Education (IJE) \\nISSN : 1839-519N 2974-5962 (Print)***February Issue ***\\nhttp://skycs.org/jounals/ijaie/Home.html\\n\\xa0Submission System.\\xa0\\nScope\\n',\n",
              " 'Porn and Its Uses\\nWednesday, February 26, 2020 - 3:58pm\\nSynoptique: An Online Journal of Film and Moving Image Studies\\nThursday, April 30, 2020\\nCall for Submissions: Porn and Its UsesSpecial Issue of\\xa0Synoptique: An Online Journal of Film and Moving Image Studies\\xa0French version on\\xa0synoptique.ca\\xa0Synoptique\\xa0is inviting submissions for an upcoming special issue entitled “Porn and Its Uses.” Responding to the\\n',\n",
              " 'Envisioning Temporality in South Asian Studies: Anticolonial Past, Resistant Present and Radical Futures\\nWednesday, February 26, 2020 - 3:56pm\\nSritama Chatterjee\\nThursday, March 12, 2020\\nPaper proposals of 300 words and a 100 word bio-note are invited for South Asian Literary Association(SALA) nominated *guaranteed panel for MLA 2021* to be held in Toronto from 7th to 10th January, 2021\\nDeadline: 12th March, 2020.\\xa0\\nShort Description of the panel :\\nWhat are the modalities through which time is lived and imagined in South Asia? Abstracts of 300 words are invited by 12th March, 2020.\\nSritama Chatterjee, University of Pittsburgh (src88@pitt.edu)\\n',\n",
              " 'Teaching and CFP: MLA 2021, Training in Irish Studies for 2021 and Beyond: Where to Next?\\nWednesday, February 26, 2020 - 3:55pm\\nMLA Irish Languages, Literatures, and Cultures (LLC) Forum\\nTuesday, March 24, 2020\\nA recent assessment of the state of the humanities (Williams, “The New Humanities,” Chronicle of Higher Education, 14 Nov. 2019) speaks of the rise of “hybrid humanities” -- increasingly collaborative research ventures built around subjects and approaches such as the environment, digital methods, global networks, and public-facing scholarship. And proficiency, if not mastery, in a second discipline after graduate school seems to be an emerging interest (and even need) among researchers according to an upcoming report on the needs of faculty in literature and writing studies conducted by Ithaka S+R and the MLA International Bibliography.\\n',\n",
              " 'VERGE STUDIES IN GLOBAL ASIAS - Issue 9.1: Open Issue\\nWednesday, February 26, 2020 - 3:47pm\\nVERGE STUDIES IN GLOBAL ASIAS\\nMonday, November 1, 2021\\nVERGE STUDIES IN GLOBAL ASIAS\\nIssue 9.1: Open Issue\\nDeadline | November 1, 2021\\nverge@psu.edu\\n',\n",
              " \"Jameson's Postmodernism at 30 (Proposed Special Session, MLA 2021, January 7-10, Toronto, ON)\\nWednesday, February 26, 2020 - 3:47pm\\nIan Butcher / Fanshawe College\\nMonday, March 23, 2020\\nAlthough Jameson's original essay was published in the New Left Review in 1984, Postmodernism, or The Cultural Logic of Late Capitalism appeared in 1991 and became one of the definitive texts on the topic.\\n\",\n",
              " 'VERGE STUDIES IN GLOBAL ASIAS: Issue 8.2 - Visualizing Asias: Interventions in Asian and Asian Diasporic Art\\nWednesday, February 26, 2020 - 3:47pm\\nVERGE STUDIES IN GLOBAL ASIAS\\nSaturday, May 1, 2021\\nIssue 8.2- Visualizing Asias: Interventions inAsian and Asian Diasporic Art\\nEdited by Laura Kina (DePaul University) and Chang Tan (Penn State)\\nDeadline\\xa0May 1, 2021 | verge@psu.edu\\n',\n",
              " 'VERGE STUDIES IN GLOBAL ASIAS: ISSUE 8.1 - Indian Ocean Studies, Afro-Asian Affinities\\nWednesday, February 26, 2020 - 3:47pm\\nVERGE STUDIES IN GLOBAL ASIAS\\nSunday, November 1, 2020\\nIndian Ocean Studies, Afro-Asian Affinities\\nEdited by Emmanuel Bruno Jean-Francois (Penn State) &\\nNeelima Jeychandran (Penn State)\\nDeadline\\xa0November 1, 2020| verge@psu.edu\\n',\n",
              " 'VERGE STUDIES IN GLOBAL ASIAS: ISSUE 7.2 DIGITAL ASIAS\\nWednesday, February 26, 2020 - 3:47pm\\nVerge: Studies in Global Asias\\nFriday, May 1, 2020\\nVERGE STUDIES IN GLOBAL ASIAS\\nISSUE 7.2 DIGITAL ASIAS\\nEdited by Jonathan E. Abel (Penn State) ＆ Joseph Jonghyun Jeon (UC-Irvine)\\nDeadlines | verge@psu.edu\\nEssays | May 1, 2020\\n',\n",
              " 'Literary Monsters - SAMLA - November 13-15, 2020\\nWednesday, February 26, 2020 - 3:45pm\\nTracie Provost / Middle Georgia State University\\nWednesday, May 20, 2020\\nIn today\\'s culture, it\\'s almost impossible to avoid \"monsters.\"\\xa0 Straight from mythology and legend, these fantastic creatures traipse across our television screens and the pages of our books.\\xa0 Over centuries and across cultures, the inhuman have represented numerous cultural fears and, in more recent times, desires. They are Other. They are Us. This panel will explore the literal monsters--whether they be mythological, extraterrestrial, or man-made--that populate fiction and film, delving into the cultural, psychological and/or theoretical implications.\\n',\n",
              " 'Speculative Fiction - SAMLA - November 13-15, 2020\\nWednesday, February 26, 2020 - 3:45pm\\nMert Gareis / Middle Georgia State University\\nWednesday, May 20, 2020\\nSpeculative fiction covers a broad range of narrative styles and genres.\\xa0 The cohesive element that pulls works together under the category is that there is some “unrealistic” element, whether it’s magical, supernatural, or a futuristic/technological development: works that fall into the category stray from conventional realism in some way.\\xa0\\xa0 For this reason, speculative fiction can be quite broad, including everything from fantasy and magical realism to horror and science fiction—from China Miéville to Margaret Atwood to Philip K. Dick. This panel aims to explore those unrealistic elements and all their varied implications about society, politics, economics, and more.\\n',\n",
              " 'Cultures of Collectivity and Manuscript Evidence\\nWednesday, February 26, 2020 - 3:45pm\\nThe Research Group on Manuscript Evidence at the Midwest Modern Language Association\\nFriday, May 1, 2020\\nThe Research Group on Manuscript Evidence, in keeping with the MMLA conference’s theme of\\xa0“Cultures of Collectivity,”\\xa0is sponsoring panels on collecting and manuscripts, broadly conceived. Possible foci include, strictly by way of example: specific archives, collections, or even gatherings of texts in particular manuscripts; reading communities or scribal centers; book markets; and the collections of material resources involved in manuscript production. We invite all approaches—including hermeneutical, textual, art historical, codicological, and paleographical—across all time periods.\\n',\n",
              " '[UPDATE] MLA 2021 CFP: State of the Body: Health and Illness in the 21st Century\\nWednesday, February 26, 2020 - 3:45pm\\nTana Jean Welch / Florida State University College of Medicine\\nSunday, March 15, 2020\\nWhat methodologies and/or texts best help us make sense of our current bodily relationship to health, illness, and medicine? Papers utilizing posthumanism, new materialism, feminist science studies,\\xa0or other\\xa0philosophical tools are welcome. All literary genres and time periods will be considered.\\nThis cfp is purposefully broad; the focus of the panel(s) created will be more specific.\\nThis panel is sponsored by the medical humanities forum of the MLA.\\nSubmit 250- to 500-word abstracts and a CV, by March 15, 2020, to Tana Jean Welch, Florida State University College of Medicine, at\\xa0tana.welch@med.fsu.edu\\n',\n",
              " 'Foreseeing Race: The Technology and Culture of Risk Prediction after the Datalogical Turn\\nWednesday, February 26, 2020 - 11:17am\\nJournal of American Studies (Cambridge University Press)\\nSaturday, October 31, 2020\\nForeseeing Race: The Technology and Culture of Risk Prediction after the Datalogical Turn\\xa0\\nSpecial issue,\\xa0Journal of American Studies\\nEditors:\\xa0\\nGeorgiana Banita (University of Bamberg)\\nR. Joshua Scannell (The New School)\\n',\n",
              " 'Contested Archives and the Intellectual Histories of Indian Modernity: From the Precolonial to the Postcolonial\\nWednesday, February 26, 2020 - 11:12am\\nFaculty of History, University of Cambridge\\nFriday, March 20, 2020\\nCall for Papers: Workshop on Indian Intellectual History\\nFriday, 29th May, 2020. (Deadline for abstract submission: 20th March, 2020)\\nFaculty of History, University of Cambridge.\\n\\xa0\\nContested Archives and the Intellectual Histories of Indian Modernity: From the Precolonial to the Postcolonial\\n',\n",
              " 'MLA 2021 Toronto: Laughter & Feminist Critical Thought\\nWednesday, February 26, 2020 - 10:25am\\nMaggie Hennefeld / University of Minnesota\\nFriday, March 20, 2020\\nFeminist theory has always enjoyed a productive but uneasy relationship with laughter. What are the limits and potentials of laughing paradigms for the future of feminist critical thought?\\n\\xa0\\nTopics May Include (but are not limited to):\\n',\n",
              " 'Postcolonial Optimism (MLA 2021)\\nWednesday, February 26, 2020 - 10:25am\\nJeremy De Chavez and Katherine Hallemeier\\nSunday, March 15, 2020\\nOptimism is not readily\\xa0associated with the postcolonial. Indeed, postcolonial writing has been described as melancholic and postoptimistic, a repository of the injurious legacies of empire.\\xa0It is a reputation consonant with postcolonialism’s revelatory project of unmasking imperial designs in canonical texts and exposing complicity in postcolonial writing. In addition, almost by definition, the postcolonial novel expresses disillusionment with nationhood and the developmentalist logics that frame it.\\n',\n",
              " 'Technoculture Volume 10 (2020)\\nWednesday, February 26, 2020 - 10:25am\\nTechnoculture: an online journal of technology in society\\nMonday, August 3, 2020\\nFor our tenth year anniversary issue, Technoculture\\xa0is seeking critical essays and creative works from a broad range of academic disciplines that focus on cultural studies of technology, and especially on the future of the study of technology and culture.\\nEssays and creative works we publish examine the topic technology and society, or, perhaps, technologies and societies. This call is ongoing and open topic, and we encourage a broad definition of technology. Topics could include depictions of technologies that treat a wide range of subjects related to the social sciences and humanities.\\n',\n",
              " 'MSA 2020 - Millay, Lowell, Teasdale, and the ‘Sentimental’ Modern Poet\\nWednesday, February 26, 2020 - 10:24am\\nModernist Studies Association\\nFriday, March 13, 2020\\nCall for Proposals\\nMillay, Lowell, Teasdale, and the ‘Sentimental’ Modern Poet\\n\\xa0\\nModernist Studies Association\\nBrooklyn, NY\\n22-25 October 2020\\n\\xa0\\nOrganized by Sarah Parker (Loughborough University) and Francisco E. Robles (University of Notre Dame)\\n',\n",
              " \"Scandalous Short Stories\\nWednesday, February 26, 2020 - 10:24am\\nTimothy K. Nixon, SAMLA (South Atlantic Modern Language Association)\\nSunday, May 31, 2020\\nSAMLA 92 will be taking place in Jacksonville, Florida, from November 13th to the 15th. The theme of this year's conference is SCANDAL! This particular panel considers the genre of the short story juxtaposed with the conference's theme: Scandal. We welcome proposals considering short works of fiction that are scandalous, that caused a scandal, or that were inspired by scandal. By May 31st, please send a 200-word abstract, brief biography (no more than 75 words), and A/V requirements to Dr. Timothy K. Nixon, Shepherd University, at\\xa0tnixon@shepherd.edu.\\n\",\n",
              " \"Dostoevsky at 200: International Receptions (MLA 2021)\\nWednesday, February 26, 2020 - 10:24am\\nInternational Dostoevsky Society / Reception Study Society\\nSunday, March 15, 2020\\nConsiderable research has been devoted to Fyodor Dostoevsky's incorporation of non-Russian art and texts as inspiration for his writing. Comparatively less attention, however, has been to paid to the immense influence the author's own life and works have had on literature, drama, philosophy, and art.\\xa0This panel seeks to explore Dostoevsky's reception, as a man and as an author, by 20th and 21st century world writers and artists.\\xa0It is\\xa0co-sponsored by the International Dostoevsky Society and the Reception Study Society in celebration of the author's 200th year.\\nPotential topics include, but are not limited to:\\n\",\n",
              " 'Global Indigeneity (MLA 2021)\\nWednesday, February 26, 2020 - 10:24am\\nAhmed Idrissi\\nFriday, March 20, 2020\\nConsiders theoretical and political questions raised by the model of “trans-indigeneity” paying attention to indigenous mythologies, histories of settler colonialism, and questions of comparison, translation, resistance, language, and appropriation.\\xa0 Send 300-word abstract and short bio by March 20, 2020 to Ahmed Idrissi aidrissi@prdue.edu and Neville Hoad nhoad@austin.utexas.edu\\n',\n",
              " 'From Proletariat to Precariat: Representations of Class and Identity in Working-class writing from the 1930s to the present\\nWednesday, February 26, 2020 - 10:24am\\nThe University of Birmingham\\nThursday, April 30, 2020\\nWe invite submissions to an interdisciplinary conference on working -class fiction, to be held at the University of Birmingham in June.\\n\\xa0\\nIn a recent Guardian article Tim Lott laments the death of the English working-class novel and likewise that of the English working-class literary novelist. He qualifies his pronouncement, by remarking the delineation ‘English’ is used advisedly, for ‘the same is not true of Scotland’. Nevertheless, he may have also appended the modifiers ‘White’ and ‘Male’ before ‘English’ so as to complete the chain of associations traditionally linked to working-class writing.\\n',\n",
              " 'CFP Fashion and Material Culture, MPCA/ACA\\nWednesday, February 26, 2020 - 10:03am\\nLuxx Mishou, Area Chair/ The Midwest Popular Culture Association/Midwest American Culture Association\\nThursday, April 30, 2020\\nCALL FOR PAPERS, ABSTRACTS, AND PANEL PROPOSALS\\n\\xa0\\nFashion and Material Culture, MWPCA/ACA\\n\\xa0\\xa0\\nThe Fashion and Material Culture area of The Midwest Popular Culture Association/Midwest American Culture Association is now welcoming abstracts, papers, and panel proposals for its 2020 meeting in Minneapolis, Minnesota on October 2-4, 2020.\\n',\n",
              " 'International Journal of Information Technology (IJIT)\\nWednesday, February 26, 2020 - 2:01am\\nbook publisher\\nSaturday, February 29, 2020\\nInternational Journal of Information Technology (IJIT)\\nISSN : 1834-624N 2974-5962 (Print)\\n***February Issue ***http://flyccs.com/jounals/IJIT/Home.html\\n\\xa0\\nScope\\n',\n",
              " 'Refugee Forms: Essays on the Culture of Flight and Refuge (edited collection)\\nTuesday, February 25, 2020 - 11:16am\\nMike Classon Frangos\\nFriday, April 17, 2020\\nCall for Papers\\nRefugee Forms: Essays on the Culture of Flight and Refuge\\nCo-editors: Sheila Ghose (Södertörn University)Mike Classon Frangos (Linnaeus University)\\nThe edited collection Refugee Forms: Essays on the Culture of Flight and Refuge aims to bring together research on the genres, forms, media and histories of refugee migration. Chapters are invited from a range of disciplines, and interdisciplinary approaches are especially welcome. Contributions may focus on refugee migration through the lens of particular genres, forms, media or histories, addressing such topics as:\\n',\n",
              " '“Blood on the Leaves / And Blood at the Roots”: Reconsidering Forms of Enslavement and Subjection across Disciplines\\nTuesday, February 25, 2020 - 6:59am\\nUniversity of Warwick\\nMonday, April 20, 2020\\n“Blood on the Leaves / And Blood at the Roots”:\\nReconsidering Forms of Enslavement and Subjection across Disciplines\\n\\xa0\\n18th June 2020:\\nPre-conference panel on getting published & networking event for postgraduate students and early career researchers and practitioners\\nSupported bythe Institute for Advanced Studies (IAS)\\n\\xa0\\n19th-20th June 2020\\nConference at the University of Warwick, Coventry, UK\\n',\n",
              " 'Travel Literature and Transatlantic Encounters: “The Iberian Peninsula as seen from North America (1850-1950)\"\\nTuesday, February 25, 2020 - 6:18am\\nSara Prieto\\nTuesday, March 10, 2020\\nTravel Literature and Transatlantic Encounters: “The Iberian Peninsula as seen from North America (1850-1950)\"\\nUniversity of Alicante (Spain), June 4-5, 2020.\\nThis conference is part of the research project \"Exotic Spain: American Travel Literature about Spain (1900-1950)\" (ATLAS) funded by the Research and Knowledge Transfer Office of Alicante University (GRE18-14 A). The project focuses on the study of a corpus of American authors who traveled to Spain in the first half of the twentieth century, especially on those texts that look beyond the vision of Spain related to the experience of the Spanish Civil War.\\n',\n",
              " 'Ambiguity and Narratology (Interdisciplinary and Diachronic Workshop)\\nTuesday, February 25, 2020 - 3:02am\\nUniversität Tübingen, GRK 1808 Ambiguität\\nMonday, June 15, 2020\\n(with apologizes for cross posting)\\nDear all,\\nThe Research Training Group 1808: Ambiguity - Production and Perception of the Eberhard Karls Univeristät Tübingen is delighted to announce the CfP for the interdisciplinary and diachronic Workshop\\nAmbiguity and Narratology\\nTübingen, November 5-7 2020\\n',\n",
              " 'Neohelicon Special Issue: Epidemics and Plagues in Literature\\nTuesday, February 25, 2020 - 12:32am\\nNeohelicon\\nFriday, May 1, 2020\\nNeohelicon Special Issue:\\xa0Never Really Away from Us---Epidemics and Plagues in Literature\\n',\n",
              " 'VICTORIAN WOMEN NOVELISTS: NAVIGATING PLACE IN BRITISH SOCIETY\\nMonday, February 24, 2020 - 8:40pm\\nCalabria Turner, Georgia State University, SAMLA 92\\nMonday, June 1, 2020\\nBritish women novelists of the Victorian era often explored the accepted and shifting concepts of woman’s role at home, in the workplace, and in society as a whole. Charlotte Bronte, George Eliot, and Oliver Schreiner, for example, discuss a woman’s right to education and the careers open to her as well as how she chooses, if she has a choice. This panel will explore these writers’ arguments for women’s equality and examine repercussions deriving from their writing. Panelists might address such questions as how authors expressed their acceptance of or discontent with women’s position in society or whether the conversation changed as the nineteenth century came to an end. Papers should not exceed 15 minutes.\\n',\n",
              " 'ASLE panel at RMMLA Convention (October 2020)\\nMonday, February 24, 2020 - 8:40pm\\nRocky Mountain Modern Languages Association/ Association for the Study of Literature and the Environment\\nTuesday, March 31, 2020\\nProposals are now being accepted for the Association for the Study of Literature and Environment (ASLE) permanent panel at the Rocky Mountain Modern Languages Association (RMMLA) annual convention. This year’s conference will take place October 8–10 in Boulder, Colorado. Proposals on any topic related to ecocriticism and the environmental arts and humanities are welcome, including pedagogical papers. Proposals of 250–300 words should be sent to Lowell Wyse at Lowell.Wyse@gmail.com by March 31, 2020.\\n',\n",
              " 'MMLA 2020: Travel Writing/Writing Travel Session\\nMonday, February 24, 2020 - 8:40pm\\nShannon Derby/Midwest Modern Language Association\\nSunday, April 5, 2020\\nTravel is a vehicle for which to explore the condition of living, how our relationships to place shape us and our experiences, how our identities and political histories inform place, how power structures inform how we migrate (or don’t) and how that affects the places we pass through. --Bani Amor, “Getting Real About Decolonizing Travel Culture” (2017)\\n',\n",
              " 'Modernist Materialisms (MSA)\\nMonday, February 24, 2020 - 8:40pm\\nModernist Studies Association\\nMonday, March 16, 2020\\nFor most of its history, materialism was, as Althusser aptly phrased it, an “underground” tradition, dissident if not altogether heretical. And yet scholars have recently begun to show how this tradition infuses the thought of canonical figures within modernism, from Stevens to Man Ray, and how their once-overlooked engagement with objects and the material effectively subtends their ontologies and political commitments. This proposed panel invites papers that explore modernist materialisms, looking at theoretical innovations, artistic experimentations, and/or political engagements. How do modernist writers and artists rethink the orthodox ways of relating to objects, things, and nonhuman bodies?\\n',\n",
              " 'Love Beyond the (Hu)man\\nMonday, February 24, 2020 - 8:40pm\\nDr. Lilith Acadia & Dr. Clare Tebbutt, Trinity College Dublin\\nTuesday, March 31, 2020\\nLove Beyond the (Hu)man \\xa0 \\nTrinity Long Room Hub Arts & Humanities Research Institute\\nDublin, Ireland | 26 June, 2020\\n\\xa0\\nDonna Haraway and her tree snails, Alice Walker and Marley, \\nLotte Laserstein’s “Self-portrait with a cat,” Lazi’s crocodile…\\n',\n",
              " 'Fantastic (Fantasy & Science Fiction / Monsters & the Monstrous) (NEPCA Manchester, NH 10/23-24/2020)\\nMonday, February 24, 2020 - 8:40pm\\nMichael Torregrossa, Northeast Alliance for Scholarship on the Fantastic\\nMonday, June 1, 2020\\nCall for Papers on the Fantastic (Fantasy & Science Fiction / Monsters & the Monstrous)\\nThe Northeast Alliance for Scholarship on the Fantastic and the allied Fantastic Areas (Fantasy & Science Fiction and Monsters & the Monstrous) invite paper proposals for the 2020 conference of the Northeast Popular Culture/American Culture Association (NEPCA) to convene at Southern New Hampshire University in Manchester, New Hampshire, from Friday, 23 October, to Saturday, October 24.\\nThe deadline for proposals is June 1, 2020.\\n',\n",
              " \"The Robert Frost Society Call for Papers\\nMonday, February 24, 2020 - 8:40pm\\nDaniel Toomey/The Robert Frost Society\\nSunday, March 22, 2020\\nFor its MLA Convention 2021 (Toronto) Panel, the Robert Frost Society seeks papers offering fresh insights into the writing and life of Robert Frost.\\xa0 All paper topics will be considered.\\xa0 Some possible subject areas: influences on Frost's own writing and his influences on that of others; deeper analyses of overlooked or underappreciated poems, prose pieces, and plays; and analytical work that furthers our understanding of Frost's philosophical dualism.\\n\",\n",
              " '\"Energy and Infrastructure: An Environmental Humanities Roundtable\" (MLA 2021)\\nMonday, February 24, 2020 - 4:01pm\\nAssociation for the Study of Literature and Environment\\nSunday, March 1, 2020\\n\"Energy and Infrastructure: An Environmental Humanities Roundtable\" (MLA 2021)\\nJacob Goessling, Jordan B. Kinder, and Andrew B. Ross\\nA non-guaranteed roundtable organized by the Association for the Study of Literature and Environment\\n',\n",
              " 'The Final Frontier: Space, Race, and Survival in Speculative Fiction (MLA 2021)\\nMonday, February 24, 2020 - 4:01pm\\nSmaran Dayal\\nSunday, March 15, 2020\\nThis panel will investigate space exploration in speculative literatures. We particularly welcome papers that consider rhetorics of survivalism, racial supremacy, colonization, and/or ecocide that have informed speculative imaginations of space travel and planetary conquest.\\nPlease submit abstracts (~250 words) and CVs to tyler.harper569@gmail.com and sd3188@nyu.edu.Tyler Harper (New York University) and Smaran Dayal (New York University)\\n',\n",
              " 'SVOD Platforms and the Future of Television - Call for Chapter Proposals\\nMonday, February 24, 2020 - 4:01pm\\nDr. Christina Adamou and Dr. Sotiris Petridis, Aristotle University of Thessaloniki\\nFriday, May 15, 2020\\nSVOD Platforms and the Future of Television - Call for Chapter Proposals\\nEdited by Christina Adamou and Sotiris Petridis\\n\\xa0\\nDeadline for proposals: 15 May 2020\\nNotification of Acceptance: by 01 June 2020\\nDeadline for chapters: 01 October 2020\\n',\n",
              " 'Closer Together-Further Apart: Cross-Cultural Perspectives in Academia\\nMonday, February 24, 2020 - 4:00pm\\nUniversity of Utah\\nFriday, March 20, 2020\\nCall for Papers:\\nSego Graduate Student Language and Culture ConferenceDepartment of World Languages and Cultures at the University of UtahCloser Together-Further Apart: Cross-Cultural Perspectives in Academia\\nApril 10-11, 2020\\n',\n",
              " 'MMLA 2020 Popular Culture Permanent Session CFP: Fan Responses to Popular Culture\\nMonday, February 24, 2020 - 3:58pm\\nMidwest Modern Language Association\\nSunday, April 5, 2020\\nLast year, when Fox canceled the television show Lucifer, a fan campaign to save the show resulted in Netflix picking it up for another season. This was not an isolated incident. Collectives of fans, gathering both online and in person, often influence the longevity, the content, the dispersal, and the afterlife of their favorite shows, games, songs, and other popular culture artifacts. In response to the conference theme “Cultures of Collectivity,” the popular culture permanent session invites papers that investigate how both planned and spontaneous groups appropriate or influence popular culture.\\n\\xa0\\nPotential topics include, but are not limited to:\\n\\xa0 \\xa0 \\xa0 \\xa0 \\xa0 \\xa0 \\xa0 \\xa0 Fan based activism of all sorts\\n',\n",
              " 'Unedited / Under-edited Renaissance Texts\\nMonday, February 24, 2020 - 3:57pm\\nRenaissance English Text Society\\nFriday, March 27, 2020\\nUnedited / Under-edited Renaissance Texts\\nRenaissance English Text Society Panel\\nSCSC, Baltimore, October 29 – November 1, 2020\\n\\xa0\\n\\xa0\\xa0\\xa0\\xa0\\xa0\\xa0\\xa0\\xa0\\xa0\\xa0\\xa0 Abstracts are invited for the Renaissance English Text Society panel at the Sixteenth Century Society and Conference in Baltimore, 29 October - 1 November 2020. Twenty-minute papers should focus on some aspect of unedited or under-edited texts derived from manuscript and/or print witnesses written in English during the sixteenth century or first half of the seventeenth. Papers may address:\\n',\n",
              " 'MMLA 2020: Creative Writing (Poetry) CFP\\nMonday, February 24, 2020 - 3:57pm\\nMMLA Creative Writing (Poetry) Permanent Section\\nSunday, April 5, 2020\\n2020 MMLA Annual Convention: Milwaukee, Wisconsin\\nNovember 5-8, 2020\\nCreative Writing II: Poetry Permanent Section CFP\\n“Cultures of Collectivity: Community, Collaboration, and Poetic Practice”\\n',\n",
              " \"Call for Book Reviews\\nMonday, February 24, 2020 - 3:56pm\\nJournal of Popular Culture\\nMonday, June 1, 2020\\nHello:\\nI currently have several\\xa0books available for review for The Journal of Popular Culture.\\xa0 These reviews would be due May 1, 2019.\\xa0 If you have a completed Master's degree or higher, one of these books is in your field of study, and you are committed to\\xa0writing a review for us, please contact me at\\xa0t.jenkins@tcu.edu, noting your preferred title and your mailing address.\\xa0 The reviews need to be between 500 and 1,000 words and documented in MLA style.\\xa0 Further guidelines can be found at:\\xa0http://www.journalofpopularculture.com/submissions\\nMany thanks!\\nTricia Jenkins\\nTexas Christian University\\n\",\n",
              " 'Call for Papers - Journal of Literary and Cultural Studies\\nMonday, February 24, 2020 - 3:55pm\\nJournal of Literary and Cultural Studies\\nTuesday, March 31, 2020\\nSubmissions invited for the inaugural issue of the Journal of Literary and Cultural Studies. The Journal is being launched from this year to commemorate the Birth Centenary of legendary English Professor Late P. S. Sastri (Nagpur University). It’ll be published thrice a year and shall cover interdisciplinary research in all forms and genres of literature, art, and culture such as fiction, folklore, film/ theatre, travel writing, popular culture, translation, gender and sexuality studies, ecocriticism, globalization and urban studies, race, ethnicity, subaltern and Dalit studies, and all related areas.\\n',\n",
              " 'Special Issue on David Mamet in the 21st Century - Texas Studies in Literature and Language\\nMonday, February 24, 2020 - 3:55pm\\nTexas Studies in Literature and Language\\nSaturday, May 1, 2021\\nDavid Mamet in the Twenty-First Century\\na special issue of Texas Studies in Literature and Language (TSLL)\\nEdited by Douglas Bruster and Brice Ezell\\n',\n",
              " 'Finding Home: Migration, Placemaking & Research Creation Symposium\\nMonday, February 24, 2020 - 3:54pm\\nRyerson University\\nSunday, March 15, 2020\\nCall for Proposals\\nFinding Home: Migration, Placemaking & Research Creation Symposium\\nMay 22-23\\nRyerson University, Toronto\\n\\xa0\\nFinding Home: Migration, Placemaking & Research Creation, \\xa0a 2-day symposium May 22-23 at Ryerson University in Toronto, invites scholars, policy-makers, artists, migrants and other stakeholders to join us in round table discussions, performances, film screenings and workshops. The symposium is the culminating event of a SSHRC-funded 2-year international project examining the concept of home for forced migrants of all identities, using arts-based research.\\n',\n",
              " 'Romantic Interventions: From Idealism to Activism\\nMonday, February 24, 2020 - 3:54pm\\nTU Dortmund University\\nTuesday, March 31, 2020\\nCall for Papers\\nRomantic Interventions: From Idealism to Activism\\n\\xa0\\nFebruary 11-13, 2021, TU Dortmund University, Germany\\nConference Homepage: https://rominter2021.wixsite.com/tudortmund\\n',\n",
              " 'Hwa Kang English Journal\\nMonday, February 24, 2020 - 3:54pm\\nDepartment of English Language and Literature, Chinese Culture University\\nTuesday, March 31, 2020\\nCall for Papers\\nHwa Kang English Journal,\\xa0Vol. 25 (July 2020)\\n',\n",
              " 'Call for Papers | Vol 2: Issue I – Electronic Research Journal of Social Sciences and Humanities\\nMonday, February 24, 2020 - 3:54pm\\nChief Editor Dr Ahmad Saeed\\nMonday, March 30, 2020\\nCall for Papers | Vol 2: Issue I – Electronic Research Journal of Social Sciences and Humanities ( http://www.eresearchjournal.com/)\\nScope:\\n',\n",
              " 'Painful Pleasure, Pleasurable Pain\\nMonday, February 24, 2020 - 3:53pm\\nJSBC\\nWednesday, July 1, 2020\\nPainful Pleasure, Pleasurable Pain\\n\\xa0\\nCall for Contributions\\n\\xa0\\nJOURNAL FOR THE STUDY OF BRITISH CULTURES\\xa0( 2/2022)\\n\\xa0\\nGuest Editors: Sarah Schäfer-Althaus and Cornelia Wächter\\n',\n",
              " 'Supermodels of the World: RuPaul’s Drag Race as International Phenomenon\\nMonday, February 24, 2020 - 3:53pm\\nDanny Cookney / University of Salford\\nFriday, May 1, 2020\\nSupermodels of the World: RuPaul’s Drag Race as International Phenomenon\\nA One-Day Interdisciplinary Symposium\\n\\xa0\\nSchool of Arts and Media, University of Salford, UK.\\n25th\\xa0September 2020\\n\\xa0\\n\\xa0\\nSince its 2009 debut, RuPaul’s Drag Race has shifted from a niche American reality show anomaly to an award-winning global success. This one day symposium will examine its international reach with versions of the contest created in the UK, Thailand and Canada alongside, titular host, Rupaul having already hinted at further growth when teasingly asking journalists “how many countries are there?”.\\n',\n",
              " \"Journals of Decolonization\\nMonday, February 24, 2020 - 3:52pm\\nMaryam Fatima/ University of Massachusetts Amherst\\nSunday, March 15, 2020\\nThis cfp is for a special session at the Modern Language Association's annual convention in Toronto (7-10 Jan 2021)\\n\",\n",
              " 'Modernism, Empire, and the Environment (MSA 2020 Panel)\\nMonday, February 24, 2020 - 3:52pm\\nElizabeth Dinneny / University of Maryland, College Park\\nFriday, March 6, 2020\\n“Modernism, Empire, and the Environment”\\nMSA 2020 Brooklyn panel\\n22-25 October 2020\\nAbstracts due 3/6/20\\n',\n",
              " 'MLA 2021 Guaranteed Session CFP: New Flashpoints in Comics History (Deadline: 03/15/20)\\nMonday, February 24, 2020 - 3:51pm\\nModern Language Association\\nSunday, March 15, 2020\\nNew Flashpoints in Comics History\\nCall for Papers for a guaranteed roundtable panel sponsored by the Forum for Comics and Graphic Narratives at the Modern Language Association (MLA) Annual Convention, January 7-10, 2021 in Toronto, ON.\\n“For all the vibrant scholarship emerging around comics today, the medium remains a largely unplumbed and uncanonized field of texts you’ve never heard of.” —Ramzi Fawaz, “A Queer Sequence: Comics as a Disruptive Medium” (2019)\\n',\n",
              " 'MLA 2021 Special Session CFP: Decolonizing Comics and/as Activism (Deadline: 03/15/20)\\nMonday, February 24, 2020 - 3:51pm\\nModern Language Association\\nSunday, March 15, 2020\\nDecolonizing Comics and/as Activism\\nCall for papers for a non-guaranteed proposed session at the Modern Language Association (MLA) Annual Convention on January 7-10, 2021, in Toronto, Canada. This panel is sponsored by the Comics and Graphic Narrative Forum.\\n',\n",
              " 'MLA 2021 Special Session CFP: Comics and Graphic Narratives for Young Audiences (Deadline: 03/10/20)\\nMonday, February 24, 2020 - 3:51pm\\nModern Language Association\\nTuesday, March 10, 2020\\nComics and Graphic Narratives for Young Audiences\\nThis panel explores intersections between children’s literature and comics (including manga and graphic novels).\\xa0All\\xa0periods and nations welcome.\\nCall for Papers for a proposed special session at the Modern Language Association (MLA) Annual Convention on January 7-10, 2021 in Toronto, ON. This collaborative panel is jointly sponsored by the Comics and Graphic Narratives Forum and the Children’s\\xa0and Young Adult\\xa0Literature Forum.\\n',\n",
              " 'Call for Abstracts:  Theatre in a Post-Truth World: Texts, Politics, and Performance\\nMonday, February 24, 2020 - 3:51pm\\nWilliam C. Boles\\nSunday, April 19, 2020\\nIn 2016 Oxford Dictionaries named ”Post-truth” as the international word of the year, but as Lee McIntyre argues in his book Post-Truth (MIT, 2018), the concept of post-truth is not a new one, as he cites the vociferous arguments made against the cancer causing effects of cigarettes, the assault on vaccinations, and other significant moments of push-back that have occurred when the facts will out.\\xa0\\nHowever, in the 2010s the omnipresent nature of post-truth arguments has accelerated and is now an omnipresent part of our lives (on international, national, regional, and communal scales).\\nThe theatre, as one might imagine, has noticed and has responded.\\n',\n",
              " 'Scaling Trans Studies (MLA 2021)\\nMonday, February 24, 2020 - 3:50pm\\nDavy Knittle and Ava L.J. Kim, University of Pennsylvania\\nTuesday, March 10, 2020\\nIn her 2014\\xa0Transgender Studies Quarterly\\xa0article, \"The Technical Capacities of the Body, Assembling Race, Technology, and Transgender,\" Jules Gill-Peterson argues that \"if both transgender and race benefit from treatment as technical capacities of the body, it remains to explain how it is they retain their differences in this framework as well as how they are made more or less available at various ecological scales by systems of normalization and regulation\" (412).\\n',\n",
              " 'MOVE! (Conversations in Motion)\\nMonday, February 24, 2020 - 3:50pm\\nQueens College, City University of New York\\nTuesday, March 10, 2020\\nCALL FOR PAPERS\\nSeventh Annual Queens College English Graduate Conference\\xa0\\n\\xa0\\nMOVE!\\nConversations in Motion \\n\\xa0\\nConference Date: April 29, 2020\\nKeynote Speaker: Cristina Pérez Jiménez (Manhattan College)\\nSubmission Deadline: March 10, 2020\\n',\n",
              " 'SEA 2021 Biennial Conference: Call for Panels\\nMonday, February 24, 2020 - 3:50pm\\nSociety of Early Americanists\\nFriday, May 15, 2020\\nCALL FOR PANELS\\nSUBMISSION DEADLINE: May 15, 2020\\n',\n",
              " 'Violence in Art Book (Call for Submissions)\\nMonday, February 24, 2020 - 3:50pm\\nGCRR Press\\nWednesday, April 1, 2020\\nGCRR is currently seeking written or visual submissions to be anthologized in a bound publication dedicated to the theme of violence in art (or perhaps the absence of violence in art). We welcome both industry leaders and scholars from the disciplines of art, humanities, design, technology, and education to submit abstracts of their essay that will make a unique contribution to the academic study of violence and art. Abstracts or Proposals are due March 1, 2020.\\nFinal scholarly submissions should be approximately 3000 words, or 500 words and mixed media, that address one of the following:\\n',\n",
              " 'Diverse Projects on American Lit - archival, bibliographical, pedagogical, DH\\nMonday, February 24, 2020 - 3:50pm\\nResources for American Literary Study (Penn State UP)\\nFriday, March 6, 2020\\nResources for\\xa0American\\xa0Literary\\xa0Study, the leading journal of archival and bibliographical scholarship in American literature, is inviting submissions for 2020. Covering all periods of American literature,\\xa0RALS\\xa0welcomes both traditional and digital approaches to archival and bibliographical analysis. The journal also welcomes pedagogically focused submissions examining archival study in the classroom. Due to the nature of the journal, there is no minimum or maximum length for submissions, and we encourage innovative projects and approaches that will serve as resources for the field.\\n',\n",
              " 'The Age of Innocence at 100\\nMonday, February 24, 2020 - 3:50pm\\nEdith Wharton Review\\nMonday, August 31, 2020\\nThe Age of Innocence\\xa0at 100\\n',\n",
              " 'MLA 2021 - Bureaucratic Poetics\\nMonday, February 24, 2020 - 3:49pm\\nAlexandra Irimia / Western University\\nSunday, March 15, 2020\\nThis proposal for a special session panel at the 2021 MLA Convention (Toronto, Jan 7-10) invites 250-word abstracts for critical, theoretical, and comparative explorations of literary works involving bureaucratic subjects, settings, and tropes. Particular emphasis falls on clerk figures and paperwork, analyzed in their poetic and narrative complexities.\\n\\xa0\\nPlease send your abstracts to airimia2@uwo.ca by March 15.\\n\\xa0\\nOfficial call:\\nhttps://mla.confex.com/mla/2021/webprogrampreliminary/Paper12865.html\\n',\n",
              " 'MLA Toronto Roundtable: The Practice of Persistence at Access-Oriented Institutions\\nMonday, February 24, 2020 - 3:49pm\\nJoseph Donica and Leah Richards\\nTuesday, March 10, 2020\\nModern Language Association 2021 Convention, Toronto, Canada, 7-10 January 2021\\xa0\\nSession Title: \\xa0The Practice of Persistence at Access-Oriented Institutions\\n',\n",
              " 'EXTENDED DEADLINE: Cinematic Representations of Women in Modern Celebrity Culture (1900-1950) (edited collection)\\nMonday, February 24, 2020 - 3:49pm\\nLeticia Perez Alonso / Jackson State University\\nTuesday, April 7, 2020\\nWe invite proposals for contributions to an edited collection on cinematic representations of women in works of art, poetry, fiction, theater and criticism of the avant-garde. The popularization of film stars such as Blanche Sweet, Mae Marsh, Mary Pickford, Greta Garbo and Brigitte Helm shaped the cultural imaginary of modernity to such an extent that they influenced the creative activity of artists and writers in the years 1900-1950. Questions centering on feminine stardom will set the background of this collection of essays examining the intersections of vanguardism with popular culture, publicity and performance. How are images of femininity circulated and consumed by the spectators of the cinematic medium?\\n',\n",
              " 'International Conference on Challenges and Solutions in Education, Teaching and Learning\\nMonday, February 24, 2020 - 3:49pm\\nLondon Centre for Interdisciplinary Research\\nFriday, May 15, 2020\\n“Challenges and Solutions in\\xa0Education, Teaching and Learning” - International Conference26 September 2020 –\\xa0London, UKorganised by\\xa0London Centre for Interdisciplinary Research\\n',\n",
              " 'Economy and Value of Time in Boredom\\nMonday, February 24, 2020 - 3:49pm\\nMLA 2021 Special Session\\nSunday, March 15, 2020\\nThis special session invites papers examining the problem of time in boredom in 19th-20th\\xa0century literature, particularly in the context of value and economy of time in relation to boredom. Please send 250 word\\xa0abstracts and short bios by March 15, 2020\\n',\n",
              " 'Sadomasochism in Medieval Cultures\\nMonday, February 24, 2020 - 3:49pm\\nChristopher Vaccaro\\nSunday, March 15, 2020\\nPainful Pleasures: Sado-masochism in Medieval Cultures\\nEditor, Christopher T. Vaccaro\\n\\xa0\\n\\xa0\\nCall for Papers\\n',\n",
              " \"Updated - Afrofuturisms: Re-imagining Contemporary Blackness in History, Art, Technology, and Culture\\nMonday, February 24, 2020 - 11:51am\\n'BioDun Ogundayo, Tracee Howell\\nTuesday, March 31, 2020\\nAfrofuturisms: Re-imagining Contemporary Blackness in History, Art, Technology, and Culture\\n\"]"
            ]
          },
          "metadata": {
            "tags": []
          },
          "execution_count": 27
        }
      ]
    }
  ]
}