# -*- coding: utf-8 -*-
"""Allen.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JbzNyigF0kEc3Wh5Qwax-ZCjRWDmBwFV
"""

'''
Name: header / <h2 class: "node-title">.text 
Acronym 
Co-located <div class : "field-item even"> 
Submission Date: <span class : date-display-single>
Notification Date 
Conference Date
Location <div class : "field-item even"> 
'''

import requests
import time
from bs4 import BeautifulSoup

def eventExtractor(html_string):
    response = requests.get(html_string)
    soup = BeautifulSoup(response.content, "html.parser")

    contentBlock = soup.find_all("article")

    #missing bolded "updated" and "deadline for submission" text 

    event = [] 
    for article in contentBlock:
        rawText = '' 
        
        for title in (article.find_all("h2", {"class" : "node-title"})):
            if(title.text.strip() == ""):
                continue
            rawText += title.text.strip()+'\n'

        for loc in (article.find_all("div", {"class" : "field-items"})): 
            if(loc.text.strip() == ""):
                continue
            rawText += loc.text.strip()+'\n'
        
        event.append(rawText)

    return event 


data = [] 

for x in range(3):
    url = "https://call-for-papers.sas.upenn.edu/category/all/backtrack?page={}".format(x)
    print(url)
    pageEvent = eventExtractor(url)
    data += (pageEvent)

data